<div class="catalog-content-block objects-container">
<h2>Объекты</h2>
<?$APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"object_slider",
	Array(
            "IBLOCK_TYPE" => "aspro_max_content",
            "IBLOCK_ID" => "26",
            "NEWS_COUNT" => "50",
            "SORT_BY1" => "SORT",
            "SORT_ORDER1" => "ASC",
            "SORT_BY2" => "ID",
            "SORT_ORDER2" => "DESC",
            "FILTER_NAME" => "",
            "FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "PREVIEW_PICTURE",
			3 => "",
		),
            "PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
            "AJAX_MODE" => "N",
            "AJAX_OPTION_JUMP" => "N",
            "AJAX_OPTION_STYLE" => "Y",
            "AJAX_OPTION_HISTORY" => "N",
            "CACHE_TYPE" => "A",
            "CACHE_TIME" => "100000",
            "CACHE_FILTER" => "Y",
            "CACHE_GROUPS" => "N",
            "PREVIEW_TRUNCATE_LEN" => "",
            "ACTIVE_DATE_FORMAT" => "j F Y",
            "SET_TITLE" => "N",
            "SET_STATUS_404" => "Y",
            "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
            "ADD_SECTIONS_CHAIN" => "N",
            "HIDE_LINK_WHEN_NO_DETAIL" => "N",
            "DISPLAY_TOP_PAGER" => "N",
            "DISPLAY_BOTTOM_PAGER" => "N",
            "PAGER_TITLE" => "N",
            "PAGER_SHOW_ALWAYS" => "N",
            "PAGER_TEMPLATE" => "",
            "PAGER_DESC_NUMBERING" => "",
            "PAGER_SHOW_ALL" => "",
            "DISPLAY_NAME" => "N",
            "IMG_POSITION" => "right",
            "AJAX_OPTION_ADDITIONAL" => "",
            "COMPONENT_TEMPLATE" => "front_news",
            "SET_META_KEYWORDS" => "N",
            "SET_META_DESCRIPTION" => "Y",
            "INCLUDE_SUBSECTIONS" => "Y",
            "STRICT_SECTION_CHECK" => "N",
            "TITLE_BLOCK" => "",
            "TITLE_BLOCK_ALL" => "",
            "ALL_URL" => "", 
            "SIZE_IN_ROW" => "3",
            "TYPE_IMG" => "lg",
            "SHOW_SECTION_NAME" => "Y",
            "FON_BLOCK_2_COLS" => 'N',
            "BG_POSITION" => "center",
            "INCLUDE_FILE" => "",
            "SHOW_SUBSCRIBE" => "N",
            "TITLE_SHOW_FON" => "N",
            "TITLE_SUBSCRIBE" => "",
            "PAGER_BASE_LINK_ENABLE" => "N",
            "SHOW_404" => "Y",
            "IS_AJAX" => CMax::checkAjaxRequest(),
            "MESSAGE_404" => "",
            "USE_PERMISSIONS"	=>	"N",
            "USE_BG_IMAGE_ALTERNATE" => 'N',
            "ALL_BLOCK_BG" => 'Y',
            "USE_SECTIONS_TABS" => 'N',
            "USE_DATE_MIX_TABS" => 'N',
	)
);?>
</div>